logging:
  level:
    tk.mybatis: DEBUG
    com.shouzan.back: DEBUG

#    file: E:\tomcat\apache-tomcat-8.5.16-yss-qf-back\logs\log.log
spring:
  application:
    name: manage-back
  jackson:
    #        date-format: yyyy-MM-dd HH:mm:ss
    #        time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: true
  #    activemq:
  #        user: admin
  #        password: admin123
  #        broker-url: tcp://127.0.0.1:61616
  #        in-memory: true
  #        pool:
  #            enabled: true
  http:
    multipart:
      max-file-size: 102400KB
      max-request-size: 102400KB
  #    jms:
  #        pub-sub-domain: true
  redis: # y
    database: 0
    host: 10.66.151.251
    port: 6379
    password: Rfvnji08905Dbs!
    pool:
      max-active: 20
  datasource:
    name: test
    #        url: jdbc:mysql://10.66.208.104:3306/yssqf?useunicode=true&characterencoding=utf8
    #        username: root
    #        password: Rfvnji_0890
    url: jdbc:mysql://10.66.151.250:3306/szxys?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Rfvnji_08905Dbs!
    #        url: jdbc:mysql://bj-cdb-62p6dqwx.sql.tencentcdb.com:63824/yssqf?useUnicode=true&characterEncoding=UTF8
    #        username: root
    #        password: Rfvnji_0890

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.shouzan.back.entity  #解决java jar 运行报错  原先 classpath:**
  mapper-locations: classpath:mapper/**/*.xml

mapper:
  before: true
  not-empty: false
server:
  port: 7901

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    # docker 部署开启
  #        prefer-ip-address: true
  #        ip-address: 192.168.103.199
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #            defaultZone: http://localhost:8761/eureka/
      # docker 部署开启
      defaultZone: http://10.163.10.95:8761/eureka/,http://10.163.13.91:8761/eureka/

swagger:
  basepackage: com.shouzan.back
  service:
    name: Manage Back
    description: Manage Back后端服务
    developer: maB

#TODO正式上线时需要修改网关域名
constant:
  gateWayUrl: https://www.shouzan365.com
  #    gateWayUrl: http://gate.3w.dkys.org

#微信使用的参数
wx:
  token: qingfenkaifangpingtai #如果没有授权给第三方开放平台，在公众号填写开发配置的时候必须要按照我们这个填写，否则不能实现公众号的业务
  payTemplateCode: OPENTM407387946 #支付通知模板code 在微信公众号后台获取
  third:
    token: qingfenkaifangpingtai #微信第三方平台token
    encodingAesKey: asddsgfsadfdsaf2dsaf32dsfasfdsc322wsaf32fsa #微信第三方平台消息加解密key
    appid: wxbc900a4d89268ee7 #微信第三方平台APPID
    appSecret: e0b0c62ff73d68f2d24e7a70348da202 #微信第三方平台APPSECRET
  miniorder:
    appid: 123123 #点餐小程序appid
    appSecret: 123123 #点餐小程序appsecret


## 不同环境的配置信息
#reids token key
private_tokenKey: WX_XYS_SUB_ACCESSTOKEN_wxbe7087b0b9005eb3
#redis data base
private_redisDB: 4
#server path
private_path: /home/manage/back/tempFile
#tencent cos server path
private_cospath: shouzan-static/common_static/images/pro
#card Immediate use center-url
center_url: xys.shouzan365.com?type=skyl&couponId=
#Operate H5 url
operate_url: https://xys.shouzan365.com/#/bank-display-page?couponId=
