logging:
    level:
        tk.mybatis: DEBUG
        com.shouzan.task: DEBUG
spring:
    application:
        name: manage-task
    redis: # y
        database: 5
        host: 10.66.151.251
        port: 6379
        password: Rfvnji08905Dbs!
        pool:
          max-active: 20

    datasource:
        name: test
        url: jdbc:mysql://10.66.151.250:3306/szxys?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
        username: root
        password: Rfvnji_08905Dbs!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    type-aliases-package: com.shouzan.task.entity  #解决java jar 运行报错  原先 classpath:**
    mapper-locations: classpath:mapper/**/*.xml

mapper:
    before: true
    not-empty: false

server:
    port: 7905

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 192.168.103.199
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://10.163.10.95:8761/eureka/,http://10.163.13.91:8761/eureka/
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/
#            defaultZone: http://192.168.103.199:9311/eureka/
swagger:
    basepackage: manage-task
    service:
        name: Mangege task
        description: Ma task后端服务
        developer: MAtast